# Generated by Django 4.2 on 2023-04-14 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0009_tbl_subadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_cus_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_name', models.CharField(max_length=50)),
                ('cus_contact', models.CharField(max_length=10)),
                ('cus_email', models.CharField(max_length=50)),
                ('cus_address', models.CharField(max_length=100)),
                ('cus_photo', models.FileField(upload_to='CustomerPhoto/')),
                ('cus_pass', models.CharField(max_length=50)),
                ('cus_doj', models.DateField(auto_now_add=True)),
                ('cus_locplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_local_place')),
            ],
        ),
    ]
