# Generated by Django 4.2 on 2023-04-14 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_tbl_farmtype'),
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_farmer_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('far_name', models.CharField(max_length=50)),
                ('far_email', models.CharField(max_length=50)),
                ('far_contact', models.CharField(max_length=10)),
                ('far_address', models.CharField(max_length=100)),
                ('far_photo', models.FileField(upload_to='FarmerPhoto/')),
                ('far_proof', models.FileField(upload_to='FarmerproofPhoto/')),
                ('far_pass', models.CharField(max_length=50)),
                ('far_doj', models.DateField(auto_now_add=True)),
                ('farmer_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_farmtype')),
                ('locplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_local_place')),
            ],
        ),
    ]
