# Generated by Django 4.2 on 2023-04-14 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_tbl_farmtype'),
        ('Guest', '0004_delete_tbl_market_reg'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_market_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mar_name', models.CharField(max_length=50)),
                ('mar_email', models.CharField(max_length=50)),
                ('mar_contact', models.CharField(max_length=10)),
                ('mar_address', models.CharField(max_length=100)),
                ('marphoto', models.FileField(upload_to='MarketPhoto/')),
                ('marproof', models.FileField(upload_to='Marketproof/')),
                ('marpassword', models.CharField(max_length=50)),
                ('mar_doj', models.DateField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
