# Generated by Django 4.2 on 2023-04-15 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_tbl_market_reg'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_farmer_reg',
            name='far_status',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
