# Generated by Django 4.2 on 2023-04-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0006_tbl_farmer_reg_far_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_market_reg',
            name='mar_status',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
