# Generated by Django 4.2 on 2023-05-26 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0001_initial'),
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_farmer_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fquantity', models.CharField(default='1', max_length=1)),
                ('bookingid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.tbl_booking')),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Farmer.tbl_farmer_product')),
            ],
        ),
    ]
