# Generated by Django 4.2 on 2023-05-29 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0007_tbl_market_reg_mar_status'),
        ('Customer', '0003_rename_tbl_booking_tbl_farmer_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_market_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_status', models.CharField(default='0', max_length=1)),
                ('booking_date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_cus_reg')),
            ],
        ),
    ]
