# Generated by Django 4.2 on 2023-05-29 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0001_initial'),
        ('Customer', '0004_tbl_market_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_market_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mquantity', models.CharField(default='1', max_length=1)),
                ('bookingid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.tbl_market_booking')),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Market.tbl_market_product')),
            ],
        ),
    ]
