# Generated by Django 4.2 on 2023-06-03 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0006_alter_tbl_farmer_cart_fquantity_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_market_cart',
        ),
    ]
