# Generated by Django 4.2 on 2023-06-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0008_tbl_market_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_farmer_cart',
            name='fquantity',
            field=models.FloatField(default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='tbl_market_cart',
            name='mquantity',
            field=models.FloatField(default='0', max_length=1),
        ),
    ]
