# Generated by Django 4.2 on 2023-06-19 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0008_tbl_feedback_tbl_complaint'),
        ('Market', '0013_tbl_events_status'),
        ('Customer', '0010_tbl_farmer_booking_fpayment_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='applyevent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replay', models.CharField(max_length=500)),
                ('status', models.CharField(default='0', max_length=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_cus_reg')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Market.tbl_events')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_farmer_reg')),
            ],
        ),
    ]
