# Generated by Django 4.2 on 2023-06-19 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0011_applyevent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='applyevent',
        ),
    ]
