# Generated by Django 4.2 on 2023-06-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0013_applyevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyevent',
            name='replay',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
