# Generated by Django 4.2.3 on 2023-07-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0018_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_farmer_booking',
            name='date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tbl_market_booking',
            name='date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
