# Generated by Django 4.2.3 on 2023-07-10 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0019_alter_tbl_farmer_booking_date_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_farmer_cart',
            name='bookingid',
        ),
        migrations.RemoveField(
            model_name='tbl_farmer_cart',
            name='productid',
        ),
        migrations.RemoveField(
            model_name='tbl_market_booking',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tbl_market_cart',
            name='bookingid',
        ),
        migrations.RemoveField(
            model_name='tbl_market_cart',
            name='productid',
        ),
        migrations.DeleteModel(
            name='tbl_farmer_booking',
        ),
        migrations.DeleteModel(
            name='tbl_farmer_cart',
        ),
        migrations.DeleteModel(
            name='tbl_market_booking',
        ),
        migrations.DeleteModel(
            name='tbl_market_cart',
        ),
    ]
