# Generated by Django 4.2 on 2023-06-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0002_tbl_m_booking_tbl_m_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_m_cart',
            name='mquantity',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
