# Generated by Django 4.2 on 2023-06-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0003_alter_tbl_m_cart_mquantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_m_cart',
            name='mquantity',
            field=models.FloatField(default='0', max_length=1),
        ),
    ]
