# Generated by Django 4.2 on 2023-06-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0004_alter_tbl_m_cart_mquantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_farmer_product',
            name='pdt_stock',
            field=models.FloatField(),
        ),
    ]
