# Generated by Django 4.2 on 2023-06-09 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0005_alter_tbl_farmer_product_pdt_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_m_booking',
            name='booking_status',
            field=models.IntegerField(default='0'),
        ),
    ]
