# Generated by Django 4.2 on 2023-06-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0006_alter_tbl_m_booking_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_m_booking',
            name='payment_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='tbl_m_cart',
            name='cart_status',
            field=models.IntegerField(default='0'),
        ),
    ]
