# Generated by Django 4.2.3 on 2023-07-06 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0013_tbl_events_status'),
        ('Guest', '0008_tbl_feedback_tbl_complaint'),
        ('Farmer', '0008_remove_tbl_m_cart_bookingid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_m_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_status', models.IntegerField(default='0')),
                ('booking_date', models.DateField(auto_now_add=True)),
                ('payment_date', models.DateField(null=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_farmer_reg')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_m_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mquantity', models.FloatField(default='0', max_length=1)),
                ('cart_status', models.IntegerField(default='0')),
                ('bookingid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Farmer.tbl_m_booking')),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Market.tbl_market_product')),
            ],
        ),
    ]
