# Generated by Django 4.2.3 on 2023-07-06 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Farmer', '0009_tbl_m_booking_tbl_m_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_m_cart',
            name='bookingid',
        ),
        migrations.RemoveField(
            model_name='tbl_m_cart',
            name='productid',
        ),
        migrations.DeleteModel(
            name='tbl_m_booking',
        ),
        migrations.DeleteModel(
            name='tbl_m_cart',
        ),
    ]
