# Generated by Django 4.2.3 on 2023-07-08 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0017_remove_tbl_farmer_booking_user_and_more'),
        ('Farmer', '0011_tbl_m_booking_tbl_m_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_m_booking',
            name='farmer',
        ),
        migrations.RemoveField(
            model_name='tbl_m_cart',
            name='bookingid',
        ),
        migrations.RemoveField(
            model_name='tbl_m_cart',
            name='productid',
        ),
        migrations.DeleteModel(
            name='tbl_farmer_product',
        ),
        migrations.DeleteModel(
            name='tbl_m_booking',
        ),
        migrations.DeleteModel(
            name='tbl_m_cart',
        ),
    ]
