# Generated by Django 4.2.3 on 2023-07-08 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0010_initial'),
        ('Admin', '0020_tbl_catageory_tbl_complainttype_tbl_farmtype_and_more'),
        ('Market', '0015_initial'),
        ('Farmer', '0012_remove_tbl_m_booking_farmer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_m_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_status', models.IntegerField(default='0')),
                ('booking_date', models.DateField(auto_now_add=True)),
                ('payment_date', models.DateField(null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_farmer_reg')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_m_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mquantity', models.FloatField(default='0', max_length=1)),
                ('cart_status', models.IntegerField(default='0')),
                ('bookingid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Farmer.tbl_m_booking')),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Market.tbl_market_product')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_farmer_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdt_name', models.CharField(max_length=50)),
                ('pdt_rate', models.IntegerField()),
                ('pdt_dis', models.CharField(max_length=100)),
                ('pdt_stock', models.FloatField()),
                ('pdt_image', models.FileField(upload_to='FarmerProduct/')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_farmer_reg')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_subcat')),
            ],
        ),
    ]
