# Generated by Django 4.2 on 2023-04-11 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_tbl_complainttype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_complainttype',
        ),
    ]
