# Generated by Django 4.2 on 2023-04-13 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_tbl_subcat'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_local_place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_place_name', models.CharField(max_length=50)),
                ('pla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
