# Generated by Django 4.2 on 2023-04-14 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_tbl_local_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_subadmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sad_name', models.CharField(max_length=50)),
                ('sad_contact', models.CharField(max_length=10)),
                ('sad_eamil', models.CharField(max_length=50)),
                ('sad_address', models.CharField(max_length=100)),
                ('sad_photo', models.FileField(upload_to='SubadminPhoto/')),
                ('sad_pass', models.CharField(max_length=50)),
                ('sad_doj', models.DateField(auto_now_add=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_district')),
            ],
        ),
    ]
