# Generated by Django 4.2 on 2023-04-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_tbl_subadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_farmtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_type', models.CharField(max_length=50)),
            ],
        ),
    ]
