# Generated by Django 4.2 on 2023-04-17 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_tbl_farmtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_subadmin',
            old_name='sad_eamil',
            new_name='sad_email',
        ),
    ]
