# Generated by Django 4.2 on 2023-05-24 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_tbl_brand'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_brand',
        ),
    ]
