# Generated by Django 4.2 on 2023-05-25 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_delete_tbl_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_subadmin',
            name='sad_status',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
