# Generated by Django 4.2 on 2023-05-25 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0015_alter_tbl_subadmin_sad_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_subadmin',
            name='sad_status',
        ),
    ]
