# Generated by Django 4.2.3 on 2023-07-08 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0014_remove_tbl_market_product_market_and_more'),
        ('Guest', '0009_remove_tbl_cus_reg_cus_locplace_and_more'),
        ('Farmer', '0012_remove_tbl_m_booking_farmer_and_more'),
        ('Admin', '0018_tbl_catageory_cat_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_complainttype',
        ),
        migrations.DeleteModel(
            name='tbl_farmtype',
        ),
        migrations.RemoveField(
            model_name='tbl_local_place',
            name='pla',
        ),
        migrations.RemoveField(
            model_name='tbl_subadmin',
            name='district',
        ),
        migrations.RemoveField(
            model_name='tbl_subcat',
            name='cat',
        ),
        migrations.DeleteModel(
            name='tbl_catageory',
        ),
        migrations.DeleteModel(
            name='tbl_local_place',
        ),
        migrations.DeleteModel(
            name='tbl_subadmin',
        ),
        migrations.DeleteModel(
            name='tbl_subcat',
        ),
    ]
