# Generated by Django 4.2 on 2023-06-02 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0007_tbl_market_reg_mar_status'),
        ('Admin', '0018_tbl_catageory_cat_status'),
        ('Market', '0005_delete_tbl_market_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_market_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_con', models.CharField(max_length=500)),
                ('status', models.CharField(default='0', max_length=1)),
                ('sdate', models.DateField(auto_now_add=True)),
                ('rdate', models.DateField(null=True)),
                ('replay', models.CharField(max_length=500)),
                ('com_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_complainttype')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_market_reg')),
            ],
        ),
    ]
