# Generated by Django 4.2 on 2023-06-02 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0006_tbl_market_complaint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_market_complaint',
        ),
    ]
