# Generated by Django 4.2 on 2023-06-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0007_delete_tbl_market_complaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_market_product',
            name='pdt_stock',
            field=models.FloatField(),
        ),
    ]
