# Generated by Django 4.2 on 2023-06-13 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0008_tbl_feedback_tbl_complaint'),
        ('Market', '0008_alter_tbl_market_product_pdt_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_fdate', models.DateField(null=True)),
                ('event_tdate', models.DateField(null=True)),
                ('event_details', models.CharField(max_length=500)),
                ('event_photo', models.FileField(upload_to='MarketEvents/')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_market_reg')),
            ],
        ),
    ]
