# Generated by Django 4.2 on 2023-06-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0009_tbl_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_events',
            name='event_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
