# Generated by Django 4.2 on 2023-06-13 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0010_tbl_events_event_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_events',
        ),
    ]
