# Generated by Django 4.2 on 2023-06-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0012_tbl_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_events',
            name='status',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
