# Generated by Django 4.2.3 on 2023-07-08 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0017_remove_tbl_farmer_booking_user_and_more'),
        ('Farmer', '0012_remove_tbl_m_booking_farmer_and_more'),
        ('Market', '0013_tbl_events_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_market_product',
            name='market',
        ),
        migrations.RemoveField(
            model_name='tbl_market_product',
            name='subcategory',
        ),
        migrations.DeleteModel(
            name='tbl_events',
        ),
        migrations.DeleteModel(
            name='tbl_market_product',
        ),
    ]
